# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
matrix:
  include:
    - os: linux
      sudo: false
      env: R_CODECOV=true
      r:
        - oldrel
        - release
        - devel
    - os: osx
      r: release
      osx_image: xcode7.3
      latex: false
