# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - oldrel
  - release
  - devel
cache: packages
after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
matrix:
  include:
    - os: linux
      sudo: false
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode7.3
      latex: false
